# Generated by Django 5.2.8 on 2025-11-29 09:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('register_id', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('business_type', models.CharField(default='', help_text='e.g., Retail, Wholesale, Service', max_length=100)),
                ('industry', models.CharField(default='', help_text='e.g., Grocery, Electronics, Clothing', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional business description')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shop Configuration',
                'verbose_name_plural': 'Shop Configuration',
            },
        ),
    ]
