# Generated by Django 5.2.8 on 2025-11-29 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sale_status_sale_void_reason_sale_voided_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='void_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_items', to='core.cashier'),
        ),
    ]
