# Generated by Django 5.2.8 on 2025-11-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_saleitem_void_reason_saleitem_voided_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Confirmation'), ('completed', 'Completed'), ('voided', 'Voided')], default='completed', max_length=20),
        ),
    ]
