# Generated by Django 5.2.8 on 2025-11-30 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_sale_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='void_reason',
            new_name='refund_reason',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='void_reason',
            new_name='refund_reason',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='voided',
            new_name='refunded',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='voided_at',
            new_name='refunded_at',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='voided_at',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='voided_by',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='voided_by',
        ),
        migrations.AddField(
            model_name='sale',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='refund_type',
            field=models.CharField(blank=True, choices=[('cash', 'Cash Refund'), ('credit', 'Store Credit'), ('replacement', 'Product Replacement'), ('exchange', 'Product Exchange')], max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='refunded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunded_sales', to='core.cashier'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='refund_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='refund_type',
            field=models.CharField(blank=True, choices=[('cash', 'Cash Refund'), ('credit', 'Store Credit'), ('replacement', 'Product Replacement'), ('exchange', 'Product Exchange')], max_length=20),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='refunded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunded_items', to='core.cashier'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Confirmation'), ('completed', 'Completed'), ('refunded', 'Refunded')], default='completed', max_length=20),
        ),
    ]
