# Generated by Django 5.2.8 on 2025-12-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_void_reason_sale_refund_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_type',
            field=models.CharField(choices=[('unit', 'Per Unit'), ('kg', 'Per Kilogram'), ('g', 'Per Gram'), ('lb', 'Per Pound'), ('oz', 'Per Ounce')], default='unit', max_length=10),
        ),
    ]
