# Generated by Django 5.2.8 on 2025-12-02 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_barcode_to_line_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name/description of the stock take', max_length=255)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('total_products_counted', models.PositiveIntegerField(default=0)),
                ('total_discrepancy_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_stock_takes', to='core.cashier')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shopconfiguration')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_stock_takes', to='core.cashier')),
            ],
            options={
                'verbose_name': 'Stock Take',
                'verbose_name_plural': 'Stock Takes',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTakeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.DecimalField(decimal_places=2, help_text='Quantity in system at time of stock take', max_digits=10)),
                ('counted_quantity', models.DecimalField(decimal_places=2, help_text='Quantity counted during stock take', max_digits=10)),
                ('discrepancy', models.DecimalField(decimal_places=2, default=0, help_text='Difference between counted and system quantity', max_digits=10)),
                ('discrepancy_value', models.DecimalField(decimal_places=2, default=0, help_text='Value of discrepancy based on cost price', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('counted_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('stock_take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.stocktake')),
            ],
            options={
                'verbose_name': 'Stock Take Item',
                'verbose_name_plural': 'Stock Take Items',
                'unique_together': {('stock_take', 'product')},
            },
        ),
    ]
