# Generated by Django 5.2.8 on 2025-12-17 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_stocktake_stocktakeitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cashier',
            unique_together={('shop', 'name')},
        ),
    ]
