# Generated by Django 5.2.8 on 2025-12-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_shopconfiguration_master_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopconfiguration',
            name='api_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shopconfiguration',
            name='device_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shopconfiguration',
            name='owner_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
