# Generated by Django 5.2.8 on 2025-12-19 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_shopconfiguration_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashier',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashier',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_staff', to='core.cashier'),
        ),
        migrations.AddField(
            model_name='cashier',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional email for cashier', max_length=254),
        ),
        migrations.AddField(
            model_name='cashier',
            name='preferred_shift',
            field=models.CharField(blank=True, help_text='Preferred shift (e.g., morning, afternoon, night)', max_length=50),
        ),
        migrations.AddField(
            model_name='cashier',
            name='role',
            field=models.CharField(default='cashier', help_text='Role of the cashier', max_length=50),
        ),
        migrations.AddField(
            model_name='cashier',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='shift',
            name='closing_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
