# Generated by Django 5.2.8 on 2025-12-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_cashier_approved_at_cashier_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashier',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('inactive', 'Inactive'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
