# Generated by Django 5.2.8 on 2025-12-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_inactive_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashier',
            name='address',
            field=models.TextField(blank=True, help_text='Full address'),
        ),
        migrations.AddField(
            model_name='cashier',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AddField(
            model_name='cashier',
            name='department',
            field=models.CharField(blank=True, help_text='Department', max_length=100),
        ),
        migrations.AddField(
            model_name='cashier',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text='Emergency contact name', max_length=255),
        ),
        migrations.AddField(
            model_name='cashier',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, help_text='Emergency contact phone', max_length=20),
        ),
        migrations.AddField(
            model_name='cashier',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Employee ID', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='cashier',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], help_text='Gender', max_length=20),
        ),
        migrations.AddField(
            model_name='cashier',
            name='hire_date',
            field=models.DateField(blank=True, help_text='Date hired', null=True),
        ),
        migrations.AddField(
            model_name='cashier',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate if applicable', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='cashier',
            name='national_id',
            field=models.CharField(blank=True, help_text='National ID number', max_length=50),
        ),
        migrations.AddField(
            model_name='cashier',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the employee'),
        ),
        migrations.AddField(
            model_name='cashier',
            name='pay_day',
            field=models.PositiveIntegerField(blank=True, help_text='Day of the month they get paid (1-31)', null=True),
        ),
        migrations.AddField(
            model_name='cashier',
            name='payment_frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('bi_weekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('hourly', 'Hourly')], help_text='How often they get paid', max_length=20),
        ),
        migrations.AddField(
            model_name='cashier',
            name='position',
            field=models.CharField(blank=True, help_text='Job position/title', max_length=100),
        ),
        migrations.AddField(
            model_name='cashier',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile photo', null=True, upload_to='cashier_profiles/'),
        ),
        migrations.AddField(
            model_name='cashier',
            name='salary_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Salary amount', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cashier',
            name='salary_currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('ZIG', 'Zimbabwe Gold')], default='USD', help_text='Currency for salary', max_length=3),
        ),
        migrations.AddField(
            model_name='cashier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
