# Generated by Django 5.2.8 on 2025-12-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_cashier_address_cashier_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cashier',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Employee ID', max_length=50),
        ),
    ]
