# Generated by Django 5.2.8 on 2025-12-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_cashier_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subgroup',
            field=models.CharField(blank=True, help_text='Subgroup within category (e.g., Dried Foods, Fresh Products, etc.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='line_code',
            field=models.CharField(blank=True, help_text='6-digit product line code', max_length=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, help_text='Main category (e.g., Bakery, Butcher, Grocery)', max_length=100),
        ),
    ]
