# Generated by Django 5.2.8 on 2025-12-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20251223_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subgroup',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='line_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
