# Generated by Django 5.2.8 on 2025-12-23 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_product_subgroup_alter_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_code', models.CharField(choices=[('RECEIPT', 'Stock Receipt - New Delivery'), ('SALE', 'Stock Sale - Product Sold'), ('RETURN', 'Customer Return - Item Returned'), ('ADJUSTMENT', 'Manual Adjustment - Stock Count Correction'), ('DAMAGE', 'Damage/Spoilage - Items Damaged or Spoiled'), ('THEFT', 'Theft/Loss - Missing Items'), ('TRANSFER', 'Transfer - Stock Moved to/from Location'), ('STOCKTAKE', 'Stock Take - Physical Count Adjustment'), ('SUPPLIER_RETURN', 'Supplier Return - Returned to Supplier'), ('EXPIRED', 'Expired Items - Removed Due to Expiry'), ('OTHER', 'Other - Miscellaneous Reason')], max_length=20)),
                ('quantity_change', models.DecimalField(decimal_places=2, help_text='Positive for additions, negative for deductions', max_digits=10)),
                ('previous_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_number', models.CharField(blank=True, help_text='Invoice number, transaction ID, etc.', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the stock movement')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, help_text='Cost price at time of movement', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, help_text='Who performed this stock movement', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cashier')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shopconfiguration')),
            ],
            options={
                'verbose_name': 'Inventory Log',
                'verbose_name_plural': 'Inventory Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
