# Generated by Django 5.2.8 on 2025-12-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_inventory_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set to False to delist/hide product from main list'),
        ),
    ]
