# Generated by Django 5.2.8 on 2025-12-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_barcode_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='line_code',
            field=models.CharField(blank=True, help_text='Auto-generated unique identifier', max_length=100),
        ),
    ]
