# Generated by Django 5.2.8 on 2025-12-26 22:42
# Fixed migration to add missing fields instead of trying to alter non-existent barcode field

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_product_line_code'),
    ]

    operations = [
        # Add barcode field (was removed in migration 0012, needs to be re-added)
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='Primary barcode for scanning during sales', max_length=100),
        ),
        # Add receiving_notes field
        migrations.AddField(
            model_name='product',
            name='receiving_notes',
            field=models.TextField(blank=True, help_text='Notes about receiving the product'),
        ),
        # Add supplier_invoice field
        migrations.AddField(
            model_name='product',
            name='supplier_invoice',
            field=models.CharField(blank=True, help_text='Last supplier invoice number', max_length=255),
        ),
    ]
