# Generated by Django 5.2.8 on 2025-12-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_product_additional_barcodes_alter_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='receiving_notes',
            field=models.TextField(blank=True, help_text='Notes about receiving the product'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_invoice',
            field=models.CharField(blank=True, help_text='Last supplier invoice number', max_length=255),
        ),
    ]
