# Generated by Django 5.2.8 on 2025-12-27 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_stock_movement_model'),
        ('core', '0029_product_receiving_notes_product_supplier_invoice'),
    ]

    operations = [
    ]
