# Generated by Django 5.2.8 on 2025-12-27 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_merge_20251227_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('CONVERSION', 'Product Conversion'), ('TRANSFER', 'Transfer Between Products'), ('ADJUSTMENT', 'Stock Adjustment'), ('SPLIT', 'Product Splitting')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('from_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('from_line_code', models.CharField(blank=True, max_length=100)),
                ('from_barcode', models.CharField(blank=True, max_length=100)),
                ('to_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('to_line_code', models.CharField(blank=True, max_length=100)),
                ('to_barcode', models.CharField(blank=True, max_length=100)),
                ('conversion_ratio', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('cost_impact', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='stockmovement',
            new_name='core_stockm_shop_id_9a3a8b_idx',
            old_name='core_stock_shop_id_product__f0a1b4_idx',
        ),
        migrations.RenameIndex(
            model_name='stockmovement',
            new_name='core_stockm_movemen_e27bb4_idx',
            old_name='core_stock_movement__9e4c8d_idx',
        ),
        migrations.RenameIndex(
            model_name='stockmovement',
            new_name='core_stockm_transit_cfc960_idx',
            old_name='core_stock_transit_7b2e9c_idx',
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='from_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='core.product'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cashier'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shopconfiguration'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='to_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='core.product'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['status', 'transfer_type'], name='core_stockt_status_31791a_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['created_at'], name='core_stockt_created_8e0c1c_idx'),
        ),
    ]
