# Generated by Django 5.2.8 on 2025-12-27 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_enhance_stock_transfer_financial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity wasted', max_digits=10)),
                ('reason', models.CharField(choices=[('EXPIRED', 'Expired Products'), ('DAMAGED', 'Damaged Products'), ('SPOILED', 'Spoiled Products'), ('STALE', 'Stale Products'), ('CONTAMINATED', 'Contaminated Products'), ('DEFECTIVE', 'Defective Products'), ('OTHER', 'Other Reasons')], default='OTHER', max_length=20)),
                ('reason_details', models.TextField(blank=True, help_text='Detailed explanation of why items were wasted')),
                ('line_code', models.CharField(blank=True, help_text='Product line code at time of waste', max_length=100)),
                ('barcode', models.CharField(blank=True, help_text='Product barcode at time of waste', max_length=100)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, help_text='Cost price at time of waste', max_digits=10)),
                ('waste_value', models.DecimalField(decimal_places=2, default=0, help_text='Total value of wasted items', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cashier')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shopconfiguration')),
            ],
            options={
                'verbose_name': 'Waste Record',
                'verbose_name_plural': 'Waste Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop', '-created_at'], name='core_waste_shop_id_30bef3_idx'), models.Index(fields=['product', '-created_at'], name='core_waste_product_843262_idx'), models.Index(fields=['reason', '-created_at'], name='core_waste_reason_a1c79e_idx')],
            },
        ),
    ]
