# Generated by Django 5.2.8 on 2025-12-27 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_waste'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(help_text='Auto-generated batch identifier', max_length=50, unique=True)),
                ('reason', models.CharField(choices=[('EXPIRED', 'Expired Products'), ('DAMAGED', 'Damaged Products'), ('SPOILED', 'Spoiled Products'), ('STALE', 'Stale Products'), ('CONTAMINATED', 'Contaminated Products'), ('DEFECTIVE', 'Defective Products'), ('OTHER', 'Other Reasons')], default='OTHER', max_length=20)),
                ('reason_details', models.TextField(blank=True, help_text='Detailed explanation for the entire batch')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('total_waste_value', models.DecimalField(decimal_places=2, default=0, help_text='Total value of all wasted items in batch', max_digits=12)),
                ('total_waste_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Total quantity of all wasted items', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cashier')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shopconfiguration')),
            ],
            options={
                'verbose_name': 'Waste Batch',
                'verbose_name_plural': 'Waste Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='waste',
            name='shop_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waste_items', to='core.wastebatch'),
        ),
        migrations.AddIndex(
            model_name='wastebatch',
            index=models.Index(fields=['shop', '-created_at'], name='core_wasteb_shop_id_085e6f_idx'),
        ),
        migrations.AddIndex(
            model_name='wastebatch',
            index=models.Index(fields=['status', '-created_at'], name='core_wasteb_status_71c9c3_idx'),
        ),
        migrations.AddIndex(
            model_name='wastebatch',
            index=models.Index(fields=['batch_number'], name='core_wasteb_batch_n_fcd75a_idx'),
        ),
    ]
