# Generated by Django 5.2.8 on 2025-12-29 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_wastebatch_waste_shop_batch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Business date', unique=True)),
                ('status', models.CharField(choices=[('CLOSED', 'Shop Closed'), ('OPEN', 'Shop Open'), ('CLOSING', 'Shop Closing')], default='CLOSED', max_length=20)),
                ('opened_at', models.DateTimeField(blank=True, help_text='When shop was opened', null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='When shop was closed', null=True)),
                ('opening_notes', models.TextField(blank=True, help_text='Notes when opening')),
                ('closing_notes', models.TextField(blank=True, help_text='Notes when closing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, help_text='Who closed the shop', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_shop_days', to='core.cashier')),
                ('opened_by', models.ForeignKey(blank=True, help_text='Who opened the shop', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_shop_days', to='core.cashier')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shopconfiguration')),
            ],
            options={
                'verbose_name': 'Shop Day',
                'verbose_name_plural': 'Shop Days',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['shop', 'date'], name='core_shopda_shop_id_9394a3_idx'), models.Index(fields=['status'], name='core_shopda_status_734486_idx')],
            },
        ),
    ]
