# Generated by Django 5.2.8 on 2025-12-29 03:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_add_shop_day_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFloat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('float_amount', models.DecimalField(decimal_places=2, default=0, help_text='Owner-set float amount', max_digits=12)),
                ('float_set_at', models.DateTimeField(blank=True, help_text='When float was last set', null=True)),
                ('current_cash', models.DecimalField(decimal_places=2, default=0, help_text='Current cash in drawer', max_digits=12)),
                ('current_card', models.DecimalField(decimal_places=2, default=0, help_text='Current card payments in drawer', max_digits=12)),
                ('current_ecocash', models.DecimalField(decimal_places=2, default=0, help_text='Current EcoCash in drawer', max_digits=12)),
                ('current_transfer', models.DecimalField(decimal_places=2, default=0, help_text='Current bank transfers in drawer', max_digits=12)),
                ('current_total', models.DecimalField(decimal_places=2, default=0, help_text='Total current amount in drawer', max_digits=12)),
                ('session_cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('session_card_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('session_ecocash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('session_transfer_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('session_total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_cash_at_eod', models.DecimalField(decimal_places=2, default=0, help_text='Expected cash at end of day (float + cash sales)', max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Drawer'), ('INACTIVE', 'Inactive Drawer'), ('SETTLED', 'Settled at EOD')], default='INACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last time drawer was updated')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cashier')),
                ('float_set_by', models.ForeignKey(blank=True, help_text='Who set the float', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floats_set', to='core.cashier')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shopconfiguration')),
            ],
            options={
                'verbose_name': 'Cash Float',
                'verbose_name_plural': 'Cash Floats',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['shop', 'date'], name='core_cashfl_shop_id_00d489_idx'), models.Index(fields=['cashier', 'date'], name='core_cashfl_cashier_2ca11a_idx'), models.Index(fields=['status'], name='core_cashfl_status_70a537_idx')],
                'unique_together': {('shop', 'cashier', 'date')},
            },
        ),
    ]
