# Generated by Django 5.2.8 on 2025-12-30 09:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_cashfloat'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('hundreds', models.PositiveIntegerField(default=0)),
                ('fifties', models.PositiveIntegerField(default=0)),
                ('twenties', models.PositiveIntegerField(default=0)),
                ('tens', models.PositiveIntegerField(default=0)),
                ('fives', models.PositiveIntegerField(default=0)),
                ('twos', models.PositiveIntegerField(default=0)),
                ('ones', models.PositiveIntegerField(default=0)),
                ('coins', models.PositiveIntegerField(default=0)),
                ('card_receipts', models.PositiveIntegerField(default=0)),
                ('ecocash_receipts', models.PositiveIntegerField(default=0)),
                ('other_receipts', models.PositiveIntegerField(default=0)),
                ('total_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_card', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ecocash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_other', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_card', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_ecocash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_variance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('card_variance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ecocash_variance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_variance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Count in Progress'), ('COMPLETED', 'Count Completed'), ('REVIEWED', 'Count Reviewed')], default='IN_PROGRESS', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('counted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cashier')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counts_performed', to='core.cashier')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shopconfiguration')),
            ],
            options={
                'verbose_name': 'Cashier Count',
                'verbose_name_plural': 'Cashier Counts',
                'ordering': ['-counted_at'],
                'indexes': [models.Index(fields=['shop', 'date'], name='core_cashie_shop_id_1bcc18_idx'), models.Index(fields=['cashier', 'date'], name='core_cashie_cashier_93e385_idx'), models.Index(fields=['status'], name='core_cashie_status_e19c43_idx')],
                'unique_together': {('shop', 'cashier', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ReconciliationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('AWAITING_COUNTS', 'Awaiting Cashier Counts'), ('COMPLETED', 'Completed'), ('RECONCILED', 'Fully Reconciled')], default='NOT_STARTED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_expected_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_counted_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_variance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opening_notes', models.TextField(blank=True)),
                ('closing_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_sessions_completed', to='core.cashier')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shopconfiguration')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_sessions_started', to='core.cashier')),
            ],
            options={
                'verbose_name': 'Reconciliation Session',
                'verbose_name_plural': 'Reconciliation Sessions',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['shop', 'date'], name='core_reconc_shop_id_807a4c_idx'), models.Index(fields=['status'], name='core_reconc_status_1ccafb_idx')],
            },
        ),
    ]
