# Generated by Django 5.2.8 on 2026-01-03 23:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_cashiercount_reconciliationsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date for these exchange rates', unique=True)),
                ('usd_to_zig', models.DecimalField(decimal_places=6, default=1.0, help_text='1 US Dollar equals this many Zimbabwe Dollars', max_digits=10, validators=[django.core.validators.MinValueValidator(1e-06)])),
                ('usd_to_rand', models.DecimalField(decimal_places=6, default=18.5, help_text='1 US Dollar equals this many South African Rand', max_digits=10, validators=[django.core.validators.MinValueValidator(1e-06)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(default='system', help_text='Who updated these rates', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether these rates are currently active')),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='core_exchan_date_ae8b68_idx'), models.Index(fields=['is_active'], name='core_exchan_is_acti_de3b34_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(choices=[('usd_to_zig', 'USD to ZIG'), ('usd_to_rand', 'USD to RAND')], max_length=20)),
                ('old_value', models.DecimalField(decimal_places=6, max_digits=10)),
                ('new_value', models.DecimalField(decimal_places=6, max_digits=10)),
                ('changed_by', models.CharField(max_length=100)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('exchange_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.exchangerate')),
            ],
            options={
                'verbose_name': 'Exchange Rate History',
                'verbose_name_plural': 'Exchange Rate History',
                'ordering': ['-changed_at'],
            },
        ),
    ]
