# Generated by Django 5.2.8 on 2026-01-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_update_exchange_rates_simplified'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopconfiguration',
            name='base_currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('ZIG', 'Zimbabwe Gold'), ('RAND', 'South African Rand')], default='USD', help_text='Primary currency for the shop', max_length=4),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='salary_currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('ZIG', 'Zimbabwe Gold'), ('RAND', 'South African Rand')], default='USD', help_text='Currency for salary', max_length=4),
        ),
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('ZIG', 'Zimbabwe Gold'), ('RAND', 'South African Rand')], default='USD', max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('ZIG', 'Zimbabwe Gold'), ('RAND', 'South African Rand')], default='USD', max_length=4),
        ),
        migrations.AlterField(
            model_name='sale',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('ZIG', 'Zimbabwe Gold'), ('RAND', 'South African Rand')], default='USD', max_length=4),
        ),
        migrations.AlterField(
            model_name='stafflunch',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('ZIG', 'Zimbabwe Gold'), ('RAND', 'South African Rand')], default='USD', max_length=4),
        ),
    ]
