# Generated by Django 5.2.8 on 2026-01-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_shopconfiguration_base_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashfloat',
            name='current_card_rand',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current RAND card payments in drawer', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='current_card_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current USD card payments in drawer', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='current_card_zig',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current ZIG card payments in drawer', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='current_cash_rand',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current RAND cash in drawer', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='current_cash_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current USD cash in drawer', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='current_cash_zig',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current ZIG cash in drawer', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='current_ecocash_rand',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current RAND EcoCash in drawer', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='current_ecocash_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current USD EcoCash in drawer', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='current_ecocash_zig',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current ZIG EcoCash in drawer', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='current_total_rand',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current total RAND in drawer', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='current_total_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current total USD in drawer', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='current_total_zig',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current total ZIG in drawer', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='current_transfer_rand',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current RAND bank transfers in drawer', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='current_transfer_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current USD bank transfers in drawer', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='current_transfer_zig',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current ZIG bank transfers in drawer', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='session_card_sales_rand',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Session card sales in RAND', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='session_card_sales_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Session card sales in USD', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='session_card_sales_zig',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Session card sales in ZIG', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='session_cash_sales_rand',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Session cash sales in RAND', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='session_cash_sales_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Session cash sales in USD', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='session_cash_sales_zig',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Session cash sales in ZIG', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='session_ecocash_sales_rand',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Session EcoCash sales in RAND', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='session_ecocash_sales_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Session EcoCash sales in USD', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='session_ecocash_sales_zig',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Session EcoCash sales in ZIG', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='session_total_sales_rand',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Session total sales in RAND', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='session_total_sales_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Session total sales in USD', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='session_total_sales_zig',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Session total sales in ZIG', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='session_transfer_sales_rand',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Session transfer sales in RAND', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='session_transfer_sales_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Session transfer sales in USD', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='session_transfer_sales_zig',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Session transfer sales in ZIG', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cashfloat',
            name='current_card',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current card payments in drawer (USD only)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cashfloat',
            name='current_cash',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current cash in drawer (USD only)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cashfloat',
            name='current_ecocash',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current EcoCash in drawer (USD only)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cashfloat',
            name='current_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total current amount in drawer (USD only)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cashfloat',
            name='current_transfer',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current bank transfers in drawer (USD only)', max_digits=12),
        ),
    ]
