# Generated by Django 5.2.8 on 2026-01-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_cashfloat_current_card_rand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('ZIG', 'Zimbabwe Gold'), ('RAND', 'South African Rand')], default='USD', help_text='Currency actually received for payment', max_length=4),
        ),
        migrations.AlterField(
            model_name='sale',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('ZIG', 'Zimbabwe Gold'), ('RAND', 'South African Rand')], default='USD', help_text='Currency of the product prices', max_length=4),
        ),
    ]
