# Generated by Django 5.2.8 on 2026-01-06 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_sale_payment_currency_alter_sale_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='exchange_rate_used',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate used if payment currency differs from wallet currency', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='wallet_account',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('ZIG', 'Zimbabwe Gold'), ('RAND', 'South African Rand')], default='USD', help_text='Which currency wallet received this sale (ZIG, USD, or RAND)', max_length=4),
        ),
        migrations.CreateModel(
            name='CurrencyWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_usd', models.DecimalField(decimal_places=2, default=0, help_text='USD balance', max_digits=15)),
                ('balance_zig', models.DecimalField(decimal_places=2, default=0, help_text='ZIG balance', max_digits=15)),
                ('balance_rand', models.DecimalField(decimal_places=2, default=0, help_text='RAND balance', max_digits=15)),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='core.shopconfiguration')),
            ],
            options={
                'verbose_name': 'Currency Wallet',
                'verbose_name_plural': 'Currency Wallets',
            },
        ),
        migrations.CreateModel(
            name='CurrencyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('SALE', 'Sale Revenue'), ('REFUND', 'Refund'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('EXCHANGE', 'Currency Exchange'), ('ADJUSTMENT', 'Manual Adjustment')], max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('ZIG', 'Zimbabwe Gold'), ('RAND', 'South African Rand')], max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reference_type', models.CharField(blank=True, help_text="e.g., 'Sale', 'Refund'", max_length=50)),
                ('reference_id', models.PositiveIntegerField(blank=True, help_text='ID of the related record', null=True)),
                ('description', models.TextField(blank=True)),
                ('exchange_rate_used', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cashier')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='core.shopconfiguration')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.currencywallet')),
            ],
            options={
                'verbose_name': 'Currency Transaction',
                'verbose_name_plural': 'Currency Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop', 'currency', '-created_at'], name='core_curren_shop_id_be928c_idx'), models.Index(fields=['transaction_type', '-created_at'], name='core_curren_transac_655181_idx'), models.Index(fields=['reference_type', 'reference_id'], name='core_curren_referen_eb3970_idx')],
            },
        ),
    ]
