# Generated by Django 5.2.8 on 2026-01-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_sale_exchange_rate_used_sale_wallet_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashiercount',
            name='expected_cash_rand',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cashiercount',
            name='expected_cash_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='reconciliationsession',
            name='total_counted_cash_rand',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='reconciliationsession',
            name='total_counted_cash_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='reconciliationsession',
            name='total_expected_cash_rand',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='reconciliationsession',
            name='total_expected_cash_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
