# Generated by Django 5.2.8 on 2026-01-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_add_multicurrency_cashier_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashfloat',
            name='float_amount_rand',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Owner-set float amount (RAND)', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='float_amount_zig',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Owner-set float amount (ZIG)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='cashfloat',
            name='float_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Owner-set float amount (USD)', max_digits=12),
        ),
    ]
