# Generated by Django 5.2.8 on 2026-01-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_cashfloat_float_amount_rand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashfloat',
            name='expected_cash_rand',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Expected RAND cash at EOD (float + cash sales)', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='expected_cash_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Expected USD cash at EOD (float + cash sales)', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashfloat',
            name='expected_cash_zig',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Expected ZIG cash at EOD (float + cash sales)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='cashfloat',
            name='expected_cash_at_eod',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Expected cash at end of day (float + cash sales) - USD only', max_digits=12),
        ),
    ]
