# Generated by Django 5.2.8 on 2026-01-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_cashfloat_expected_cash_rand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashier',
            name='drawer_access',
            field=models.BooleanField(default=True, help_text='Whether this cashier has permission to access and manage cash drawers'),
        ),
    ]
