# Generated by Django 5.2.8 on 2026-01-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_add_cashier_drawer_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashier',
            name='drawer_access',
        ),
    ]
