# Generated by Django 5.2.8 on 2026-01-08 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_remove_cashier_drawer_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='shop_day',
            field=models.ForeignKey(blank=True, help_text='The shop day this sale belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='core.shopday'),
        ),
    ]
