# Generated by Django 5.2.8 on 2026-01-09 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_business_hours_timezone'),
        ('core', '0048_add_shop_day_to_sale'),
    ]

    operations = [
    ]
