# Generated by Django 5.2.8 on 2026-01-09 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_stafflunch_product_alter_stafflunch_total_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafflunch',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_lunches', to='core.cashier'),
        ),
    ]
