# Generated by Django 5.2.8 on 2026-01-10 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_salepayment_split_payments'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='salepayment',
            new_name='core_salepa_sale_id_669d4e_idx',
            old_name='salepayment_sale_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='salepayment',
            new_name='core_salepa_currenc_5942de_idx',
            old_name='salepayment_currency_idx',
        ),
    ]
