# Generated by Django 5.2.8 on 2026-01-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_rename_salepayment_sale_created_at_idx_core_salepa_sale_id_669d4e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('ecocash', 'EcoCash'), ('card', 'Card'), ('transfer', 'Bank Transfer'), ('split', 'Split Payment')], max_length=20),
        ),
    ]
