# Generated by Django 5.2.8 on 2026-01-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_cashiercount_detailed_denominations'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashiercount',
            name='rand_1',
            field=models.PositiveIntegerField(default=0, help_text='RAND 1'),
        ),
        migrations.AddField(
            model_name='cashiercount',
            name='rand_10',
            field=models.PositiveIntegerField(default=0, help_text='RAND 10'),
        ),
        migrations.AddField(
            model_name='cashiercount',
            name='rand_100',
            field=models.PositiveIntegerField(default=0, help_text='RAND 100'),
        ),
        migrations.AddField(
            model_name='cashiercount',
            name='rand_2',
            field=models.PositiveIntegerField(default=0, help_text='RAND 2'),
        ),
        migrations.AddField(
            model_name='cashiercount',
            name='rand_20',
            field=models.PositiveIntegerField(default=0, help_text='RAND 20'),
        ),
        migrations.AddField(
            model_name='cashiercount',
            name='rand_200',
            field=models.PositiveIntegerField(default=0, help_text='RAND 200'),
        ),
        migrations.AddField(
            model_name='cashiercount',
            name='rand_5',
            field=models.PositiveIntegerField(default=0, help_text='RAND 5'),
        ),
        migrations.AddField(
            model_name='cashiercount',
            name='rand_50',
            field=models.PositiveIntegerField(default=0, help_text='RAND 50'),
        ),
        migrations.AddField(
            model_name='cashiercount',
            name='total_cash_rand',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
