# Generated by Django 5.2.8 on 2026-01-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_cashiercount_rand_1_cashiercount_rand_10_and_more'),
    ]

    operations = [
        # USD Coin Denominations
        migrations.AddField(
            model_name='cashiercount',
            name='usd_1_coin',
            field=models.PositiveIntegerField(default=0, help_text='$1 coins (Sacagawea/Susan B)'),
        ),
        migrations.AddField(
            model_name='cashiercount',
            name='usd_0_50',
            field=models.PositiveIntegerField(default=0, help_text='50 cents (half dollar)'),
        ),
        migrations.AddField(
            model_name='cashiercount',
            name='usd_0_25',
            field=models.PositiveIntegerField(default=0, help_text='25 cents (quarter)'),
        ),
        migrations.AddField(
            model_name='cashiercount',
            name='usd_0_10',
            field=models.PositiveIntegerField(default=0, help_text='10 cents (dime)'),
        ),
        migrations.AddField(
            model_name='cashiercount',
            name='usd_0_05',
            field=models.PositiveIntegerField(default=0, help_text='5 cents (nickel)'),
        ),
        migrations.AddField(
            model_name='cashiercount',
            name='usd_0_01',
            field=models.PositiveIntegerField(default=0, help_text='1 cent (penny)'),
        ),
        # ZIG Coin Denominations
        migrations.AddField(
            model_name='cashiercount',
            name='zig_0_50',
            field=models.PositiveIntegerField(default=0, help_text='ZiG 50 cents'),
        ),
        # RAND Coin Denominations
        migrations.AddField(
            model_name='cashiercount',
            name='rand_0_50',
            field=models.PositiveIntegerField(default=0, help_text='50 cents'),
        ),
        migrations.AddField(
            model_name='cashiercount',
            name='rand_0_20',
            field=models.PositiveIntegerField(default=0, help_text='20 cents'),
        ),
        migrations.AddField(
            model_name='cashiercount',
            name='rand_0_10',
            field=models.PositiveIntegerField(default=0, help_text='10 cents'),
        ),
        migrations.AddField(
            model_name='cashiercount',
            name='rand_0_05',
            field=models.PositiveIntegerField(default=0, help_text='5 cents'),
        ),
    ]
