# Generated by Django 5.2.8 on 2026-01-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_add_coin_denominations'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashiercount',
            name='cash_variance_rand',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cashiercount',
            name='cash_variance_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cashiercount',
            name='cash_variance_zig',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cashiercount',
            name='expected_cash_zig',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='reconciliationsession',
            name='total_counted_cash_zig',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='reconciliationsession',
            name='total_expected_cash_zig',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='reconciliationsession',
            name='variance_rand',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='reconciliationsession',
            name='variance_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='reconciliationsession',
            name='variance_zig',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
