# Generated by Django 5.2.8 on 2026-01-29 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_cashier_archive'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cashiercountarchive',
            new_name='core_cashie_shop_id_52310c_idx',
            old_name='core_cashie_shop_id_f81286_idx',
        ),
        migrations.RenameIndex(
            model_name='cashiercountarchive',
            new_name='core_cashie_cashier_5843c9_idx',
            old_name='core_cashie_cashier_0c3a0e_idx',
        ),
        migrations.RenameIndex(
            model_name='cashiercountarchive',
            new_name='core_cashie_status_0e3c4d_idx',
            old_name='core_cashie_status_b5f88c_idx',
        ),
    ]
