import React, { useEffect, useState, useCallback } from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  StyleSheet,
  ScrollView,
  Alert,
  ActivityIndicator,
  TextInput,
  Modal,
  Platform,
} from 'react-native';
import { useNavigation } from '@react-navigation/native';
import { shopAPI } from '../services/api';
import { shopStorage } from '../services/storage';
import { ROUTES } from '../constants/navigation';

const ProductSplitScreen = () => {
  const navigation = useNavigation();
  
  // State management
  const [loading, setLoading] = useState(false);
  const [shopCredentials, setShopCredentials] = useState(null);
  
  // Product selection
  const [sourceLineCode, setSourceLineCode] = useState('');
  const [sourceBarcode, setSourceBarcode] = useState('');
  const [sourceQuantity, setSourceQuantity] = useState('');
  const [sourceProduct, setSourceProduct] = useState(null);
  const [sourceProductInfo, setSourceProductInfo] = useState(null);
  const [searchingSource, setSearchingSource] = useState(false);
  
  // Split configuration
  const [splitRatio, setSplitRatio] = useState('half'); // half, quarter, third, custom
  const [customRatio, setCustomRatio] = useState('');
  const [newProductName, setNewProductName] = useState('');
  const [newProductPrice, setNewProductPrice] = useState('');
  const [splitReason, setSplitReason] = useState('');
  
  // Calculated values
  const [calculatedSplitQuantity, setCalculatedSplitQuantity] = useState('');
  const [calculatedNewCostPrice, setCalculatedNewCostPrice] = useState('');
  const [autoGeneratedLineCode, setAutoGeneratedLineCode] = useState('');
  
  // Preview and validation
  const [showPreview, setShowPreview] = useState(false);
  const [validationResult, setValidationResult] = useState(null);

  useEffect(() => {
    loadShopCredentials();
    
    // Add web-specific scrolling CSS
    if (Platform.OS === 'web') {
      const style = document.createElement('style');
      style.textContent = `
        .product-split-scroll {
          overflow-y: auto !important;
          overflow-x: hidden !important;
          height: 100vh !important;
        }
      `;
      document.head.appendChild(style);
      
      return () => {
        document.head.removeChild(style);
      };
    }
  }, []);

  const loadShopCredentials = async () => {
    try {
      const credentials = await shopStorage.getCredentials();
      if (credentials) {
        setShopCredentials(credentials);
      } else {
        navigation.replace(ROUTES.LOGIN);
      }
    } catch (error) {
      console.error('❌ Error loading credentials:', error);
      navigation.replace(ROUTES.LOGIN);
    }
  };

  const formatCurrency = (amount) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 2,
    }).format(amount);
  };

  const getAuthHeaders = async () => {
    const credentials = await shopStorage.getCredentials();
    if (!credentials) {
      throw new Error('Shop credentials not found. Please log in again.');
    }
    
    const isShopOwner = !credentials.cashier_info;
    const shopId = credentials.shop_info?.shop_id || credentials.shop_id;
    const cashierId = credentials.cashier_info?.id;
    
    const headers = {
      'X-Shop-ID': shopId
    };
    
    // Only add cashier ID if this is a cashier (not shop owner)
    if (!isShopOwner && cashierId) {
      headers['X-Cashier-ID'] = cashierId;
    }
    
    console.log('🔑 Auth headers created:', headers);
    console.log('🔑 Is shop owner:', isShopOwner);
    console.log('🔑 Has cashier info:', !!credentials.cashier_info);
    
    return { headers, isShopOwner, credentials };
  };

  const searchSourceProduct = async (identifier) => {
    if (!identifier.trim()) return;
    
    setSearchingSource(true);
    
    try {
      const { headers } = await getAuthHeaders();
      
      const response = await shopAPI.findProductForTransfer({
        identifier: identifier.trim()
      }, {
        headers: headers
      });
      
      if (response.data.success) {
        setSourceProduct(response.data.data.product);
        setSourceProductInfo(response.data.data);
        
        // Auto-generate new product name based on source
        const sourceName = response.data.data.product.name;
        let splitSuffix = '';
        
        switch (splitRatio) {
          case 'half':
            splitSuffix = ' (Half)';
            break;
          case 'quarter':
            splitSuffix = ' (Quarter)';
            break;
          case 'third':
            splitSuffix = ' (Third)';
            break;
          case 'custom':
            splitSuffix = ` (${customRatio})`;
            break;
        }
        
        setNewProductName(sourceName + splitSuffix);
        
        // Auto-calculate new price (proportional to split ratio)
        calculateSplitValues(response.data.data.product);
      } else {
        Alert.alert('Product Not Found', response.data.error);
        setSourceProduct(null);
        setSourceProductInfo(null);
      }
    } catch (error) {
      console.error('❌ Error finding product:', error);
      Alert.alert('Error', 'Failed to find product. Please try again.');
      setSourceProduct(null);
      setSourceProductInfo(null);
    } finally {
      setSearchingSource(false);
    }
  };

  const calculateSplitValues = (product) => {
    if (!product || !sourceQuantity) return;
    
    const sourceQty = parseFloat(sourceQuantity);
    const sourceCost = parseFloat(product.cost_price) || 0;
    const sourcePrice = parseFloat(product.price) || 0;
    
    let ratio = 1;
    switch (splitRatio) {
      case 'half':
        ratio = 0.5;
        break;
      case 'quarter':
        ratio = 0.25;
        break;
      case 'third':
        ratio = 0.33;
        break;
      case 'custom':
        ratio = parseFloat(customRatio) || 1;
        break;
    }
    
    // Calculate split quantity
    const splitQty = sourceQty * ratio;
    setCalculatedSplitQuantity(splitQty.toString());
    
    // Calculate new cost price (proportional)
    const newCostPrice = sourceCost * ratio;
    setCalculatedNewCostPrice(newCostPrice.toFixed(2));
    
    // Auto-generate line code for new product
    generateLineCode();
  };

  const generateLineCode = () => {
    // Generate random 8-digit line code
    const code = Math.floor(10000000 + Math.random() * 90000000).toString();
    setAutoGeneratedLineCode(code);
  };

  const handleSplitRatioChange = (ratio) => {
    setSplitRatio(ratio);
    if (sourceProduct) {
      calculateSplitValues(sourceProduct);
    }
  };

  const handleSourceQuantityChange = (qty) => {
    setSourceQuantity(qty);
    if (sourceProduct) {
      calculateSplitValues(sourceProduct);
    }
  };

  const getValidationStatus = () => {
    const issues = [];
    
    if (!sourceProduct) issues.push('Select a source product');
    if (!sourceQuantity || parseFloat(sourceQuantity) <= 0) issues.push('Enter a valid source quantity');
    if (splitRatio === 'custom' && (!customRatio || parseFloat(customRatio) <= 0)) issues.push('Enter a valid custom split ratio');
    if (!newProductName.trim()) issues.push('Enter a name for the new product');
    if (!splitReason.trim()) issues.push('Provide a reason for splitting');
    if (!calculatedSplitQuantity) issues.push('Calculate split values (check quantity and ratio)');
    if (!autoGeneratedLineCode) issues.push('Generate line code');
    
    return issues;
  };

  const validateSplit = async () => {
    console.log('🔍 validateSplit called');
    console.log('Source product:', sourceProduct);
    console.log('Source quantity:', sourceQuantity);
    console.log('Split ratio:', splitRatio);
    console.log('Custom ratio:', customRatio);
    console.log('New product name:', newProductName);
    console.log('Split reason:', splitReason);
    console.log('Calculated split quantity:', calculatedSplitQuantity);
    console.log('Calculated new cost price:', calculatedNewCostPrice);
    console.log('Auto-generated line code:', autoGeneratedLineCode);
    
    // Validation checks
    if (!sourceProduct) {
      Alert.alert('Validation Error', 'Please select a source product to split');
      return;
    }
    
    if (!sourceQuantity || parseFloat(sourceQuantity) <= 0) {
      Alert.alert('Validation Error', 'Please enter a valid source quantity');
      return;
    }
    
    if (splitRatio === 'custom' && (!customRatio || parseFloat(customRatio) <= 0)) {
      Alert.alert('Validation Error', 'Please enter a valid custom split ratio');
      return;
    }
    
    if (!newProductName.trim()) {
      Alert.alert('Validation Error', 'Please enter a name for the new product');
      return;
    }
    
    if (!splitReason.trim()) {
      Alert.alert('Validation Error', 'Please provide a reason for splitting');
      return;
    }
    
    // Check if calculated values exist
    if (!calculatedSplitQuantity || !autoGeneratedLineCode) {
      Alert.alert('Validation Error', 'Please ensure all calculations are complete. Try changing the split ratio or quantity.');
      return;
    }
    
    // Check if source has enough stock
    const availableStock = parseFloat(sourceProductInfo?.current_stock || 0);
    const requiredQuantity = parseFloat(sourceQuantity);
    
    if (availableStock < requiredQuantity) {
      Alert.alert('Insufficient Stock', 
        `Insufficient stock. Available: ${availableStock}, Required: ${requiredQuantity}`);
      return;
    }
    
    console.log('✅ All validation passed, showing preview');
    setShowPreview(true);
  };

  const processSplit = async () => {
    console.log('🚀 processSplit called');
    setLoading(true);
    
    try {
      const { headers } = await getAuthHeaders();
      console.log('🔑 Auth headers:', headers);
      
      // Create the split transfer data
      const transferData = {
        transfer_type: 'SPLIT',
        from_line_code: sourceProduct.line_code,
        from_barcode: sourceProduct.barcode,
        from_quantity: parseFloat(sourceQuantity),
        to_line_code: autoGeneratedLineCode, // Auto-generated line code
        to_barcode: '', // Will be empty for new product
        to_quantity: parseFloat(calculatedSplitQuantity),
        reason: splitReason,
        notes: `Product split: ${sourceProduct.name} -> ${newProductName}`,
        // Additional data for new product creation
        new_product_data: {
          name: newProductName,
          price: parseFloat(newProductPrice) || (sourceProduct.price * (splitRatio === 'half' ? 0.6 : splitRatio === 'quarter' ? 0.4 : 0.5)),
          cost_price: parseFloat(calculatedNewCostPrice),
          category: sourceProduct.category,
          currency: sourceProduct.currency
        }
      };
      
      console.log('📦 Transfer data:', transferData);
      
      const response = await shopAPI.createTransfer(transferData, {
        headers: headers
      });
      
      console.log('📡 API Response:', response);
      
      if (response.data.success) {
        Alert.alert(
          'Success',
          `Product split completed successfully!\n\n` +
          `• ${sourceQuantity} units of ${sourceProduct.name} split into\n` +
          `• ${calculatedSplitQuantity} units of ${newProductName}\n` +
          `• New line code: ${autoGeneratedLineCode}`,
          [
            {
              text: 'OK',
              onPress: () => {
                resetForm();
                setShowPreview(false);
              }
            }
          ]
        );
      } else {
        Alert.alert('Split Failed', response.data.error || 'Unknown error occurred');
      }
    } catch (error) {
      console.error('❌ Error processing split:', error);
      Alert.alert('Error', 'Failed to process product split. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const resetForm = () => {
    setSourceLineCode('');
    setSourceBarcode('');
    setSourceQuantity('');
    setSourceProduct(null);
    setSourceProductInfo(null);
    setSplitRatio('half');
    setCustomRatio('');
    setNewProductName('');
    setNewProductPrice('');
    setSplitReason('');
    setCalculatedSplitQuantity('');
    setCalculatedNewCostPrice('');
    setAutoGeneratedLineCode('');
    setValidationResult(null);
  };

  const renderHeader = () => (
    <View style={styles.header}>
      <TouchableOpacity onPress={() => navigation.goBack()}>
        <Text style={styles.backButton}>← Back</Text>
      </TouchableOpacity>
      <Text style={styles.headerTitle}>✂️ Product Split</Text>
      <TouchableOpacity onPress={resetForm}>
        <Text style={styles.resetButton}>↻ Reset</Text>
      </TouchableOpacity>
    </View>
  );

  const renderSourceProductSection = () => (
    <View style={styles.section}>
      <Text style={styles.sectionTitle}>📦 Source Product (To Split)</Text>
      
      <View style={styles.inputRow}>
        <Text style={styles.inputLabel}>Line Code:</Text>
        <TextInput
          style={styles.input}
          value={sourceLineCode}
          onChangeText={(text) => {
            setSourceLineCode(text);
            setSourceBarcode('');
          }}
          placeholder="Enter line code"
          onBlur={() => sourceLineCode && searchSourceProduct(sourceLineCode)}
        />
      </View>
      
      <View style={styles.inputRow}>
        <Text style={styles.inputLabel}>OR Barcode:</Text>
        <TextInput
          style={styles.input}
          value={sourceBarcode}
          onChangeText={(text) => {
            setSourceBarcode(text);
            setSourceLineCode('');
          }}
          placeholder="Scan or enter barcode"
          onBlur={() => sourceBarcode && searchSourceProduct(sourceBarcode)}
        />
      </View>
      
      <View style={styles.inputRow}>
        <Text style={styles.inputLabel}>Quantity to Split:</Text>
        <TextInput
          style={styles.input}
          value={sourceQuantity}
          onChangeText={handleSourceQuantityChange}
          placeholder="Enter quantity to split"
          keyboardType="numeric"
        />
      </View>
      
      {searchingSource && (
        <View style={styles.searchingContainer}>
          <ActivityIndicator size="small" color="#3b82f6" />
          <Text style={styles.searchingText}>Searching for product...</Text>
        </View>
      )}
      
      {sourceProduct && sourceProductInfo && (
        <View style={styles.productInfo}>
          <Text style={styles.productName}>{sourceProduct.name}</Text>
          <Text style={styles.productDetails}>
            Available Stock: {sourceProductInfo.current_stock} | Status: {sourceProductInfo.stock_status}
          </Text>
          <Text style={styles.productDetails}>
            Current Price: {formatCurrency(sourceProduct.price)} | Cost: {formatCurrency(sourceProduct.cost_price)}
          </Text>
        </View>
      )}
    </View>
  );

  const renderSplitConfiguration = () => (
    <View style={styles.section}>
      <Text style={styles.sectionTitle}>⚙️ Split Configuration</Text>
      
      <Text style={styles.subsectionTitle}>Split Ratio:</Text>
      <View style={styles.splitRatioContainer}>
        {[
          { value: 'half', label: 'Half (1→2)', desc: 'Divide into 2 equal parts' },
          { value: 'quarter', label: 'Quarter (1→4)', desc: 'Divide into 4 equal parts' },
          { value: 'third', label: 'Third (1→3)', desc: 'Divide into 3 equal parts' },
          { value: 'custom', label: 'Custom Ratio', desc: 'Specify your own ratio' }
        ].map((ratio) => (
          <TouchableOpacity
            key={ratio.value}
            style={[
              styles.splitRatioButton,
              splitRatio === ratio.value && styles.splitRatioButtonActive
            ]}
            onPress={() => handleSplitRatioChange(ratio.value)}
          >
            <Text style={[
              styles.splitRatioLabel,
              splitRatio === ratio.value && styles.splitRatioLabelActive
            ]}>
              {ratio.label}
            </Text>
            <Text style={[
              styles.splitRatioDesc,
              splitRatio === ratio.value && styles.splitRatioDescActive
            ]}>
              {ratio.desc}
            </Text>
          </TouchableOpacity>
        ))}
      </View>
      
      {splitRatio === 'custom' && (
        <View style={styles.inputRow}>
          <Text style={styles.inputLabel}>Custom Ratio:</Text>
          <TextInput
            style={styles.input}
            value={customRatio}
            onChangeText={(text) => {
              setCustomRatio(text);
              if (sourceProduct) calculateSplitValues(sourceProduct);
            }}
            placeholder="e.g., 0.75 for 3/4"
            keyboardType="numeric"
          />
        </View>
      )}
      
      {calculatedSplitQuantity && (
        <View style={styles.calculationPreview}>
          <Text style={styles.calculationTitle}>📊 Split Calculation:</Text>
          <Text style={styles.calculationText}>
            {sourceQuantity} × {splitRatio === 'half' ? '0.5' : splitRatio === 'quarter' ? '0.25' : splitRatio === 'third' ? '0.33' : customRatio} = {calculatedSplitQuantity} units
          </Text>
        </View>
      )}
    </View>
  );

  const renderNewProductSection = () => (
    <View style={styles.section}>
      <Text style={styles.sectionTitle}>🆕 New Product Details</Text>
      
      <View style={styles.inputRow}>
        <Text style={styles.inputLabel}>Product Name:</Text>
        <TextInput
          style={styles.input}
          value={newProductName}
          onChangeText={setNewProductName}
          placeholder="Auto-generated name (editable)"
        />
      </View>
      
      <View style={styles.inputRow}>
        <Text style={styles.inputLabel}>Sale Price:</Text>
        <TextInput
          style={styles.input}
          value={newProductPrice}
          onChangeText={setNewProductPrice}
          placeholder={`Auto-calculated (${formatCurrency(sourceProduct?.price * (splitRatio === 'half' ? 0.6 : splitRatio === 'quarter' ? 0.4 : 0.5))})`}
          keyboardType="numeric"
        />
      </View>
      
      <View style={styles.inputRow}>
        <Text style={styles.inputLabel}>Cost Price:</Text>
        <TextInput
          style={[styles.input, styles.readOnlyInput]}
          value={calculatedNewCostPrice}
          placeholder="Auto-calculated"
          editable={false}
        />
      </View>
      
      <View style={styles.inputRow}>
        <Text style={styles.inputLabel}>Line Code:</Text>
        <TextInput
          style={[styles.input, styles.readOnlyInput]}
          value={autoGeneratedLineCode}
          placeholder="Auto-generated"
          editable={false}
        />
      </View>
      
      <View style={styles.inputRow}>
        <Text style={styles.inputLabel}>Split Reason:</Text>
        <TextInput
          style={[styles.input, styles.textArea]}
          value={splitReason}
          onChangeText={setSplitReason}
          placeholder="Why are you splitting this product?"
          multiline
          numberOfLines={3}
        />
      </View>
    </View>
  );

  const renderPreviewModal = () => (
    <Modal
      visible={showPreview}
      transparent={true}
      animationType="slide"
      onRequestClose={() => setShowPreview(false)}
    >
      <View style={styles.modalOverlay}>
        <View style={styles.modalContent}>
          <View style={styles.modalHeader}>
            <Text style={styles.modalTitle}>✂️ Product Split Preview</Text>
            <TouchableOpacity 
              style={styles.closeButton}
              onPress={() => setShowPreview(false)}
            >
              <Text style={styles.closeButtonText}>✕</Text>
            </TouchableOpacity>
          </View>
          
          <View style={styles.modalBody}>
            <Text style={styles.previewTitle}>Split Summary:</Text>
            
            <View style={styles.splitSummary}>
              <Text style={styles.summaryLabel}>Source Product:</Text>
              <Text style={styles.summaryValue}>{sourceProduct?.name}</Text>
              
              <Text style={styles.summaryLabel}>Quantity to Split:</Text>
              <Text style={styles.summaryValue}>{sourceQuantity} units</Text>
              
              <Text style={styles.summaryLabel}>Split Ratio:</Text>
              <Text style={styles.summaryValue}>
                {splitRatio === 'half' ? '1/2' : splitRatio === 'quarter' ? '1/4' : splitRatio === 'third' ? '1/3' : customRatio}
              </Text>
              
              <Text style={styles.summaryLabel}>Resulting Units:</Text>
              <Text style={styles.summaryValue}>{calculatedSplitQuantity} units</Text>
              
              <Text style={styles.summaryLabel}>New Product:</Text>
              <Text style={styles.summaryValue}>{newProductName}</Text>
              
              <Text style={styles.summaryLabel}>New Line Code:</Text>
              <Text style={styles.summaryValue}>{autoGeneratedLineCode}</Text>
              
              <Text style={styles.summaryLabel}>New Cost Price:</Text>
              <Text style={styles.summaryValue}>{formatCurrency(parseFloat(calculatedNewCostPrice) || 0)}</Text>
            </View>
            
            <View style={styles.actionPreview}>
              <Text style={styles.actionText}>
                This will create a new product and reduce the source product stock by {sourceQuantity} units.
              </Text>
            </View>
          </View>
          
          <View style={styles.modalActions}>
            <TouchableOpacity
              style={styles.cancelButton}
              onPress={() => setShowPreview(false)}
            >
              <Text style={styles.cancelButtonText}>Cancel</Text>
            </TouchableOpacity>
            
            <TouchableOpacity
              style={styles.confirmButton}
              onPress={processSplit}
              disabled={loading}
            >
              <Text style={styles.confirmButtonText}>
                {loading ? 'Processing...' : '✂️ Confirm Split'}
              </Text>
            </TouchableOpacity>
          </View>
        </View>
      </View>
    </Modal>
  );

  return (
    <ScrollView 
      style={[styles.container, Platform.OS === 'web' && styles.webScrollView]}
      contentContainerStyle={Platform.OS === 'web' ? styles.webContentContainer : styles.scrollContentContainer}
      showsVerticalScrollIndicator={Platform.OS === 'web'}
      showsHorizontalScrollIndicator={false}
    >
      {renderHeader()}
      
      {renderSourceProductSection()}
      {renderSplitConfiguration()}
      {renderNewProductSection()}
      
      {/* Action Buttons */}
      <View style={styles.actionButtons}>
        {/* Validation Status */}
        {getValidationStatus().length > 0 && (
          <View style={styles.validationStatus}>
            <Text style={styles.validationTitle}>📝 Please complete:</Text>
            {getValidationStatus().map((issue, index) => (
              <Text key={index} style={styles.validationIssue}>• {issue}</Text>
            ))}
          </View>
        )}
        
        <TouchableOpacity
          style={[
            styles.validateButton,
            (loading || !sourceProduct || getValidationStatus().length > 0) && styles.validateButtonDisabled
          ]}
          onPress={validateSplit}
          disabled={loading || !sourceProduct || getValidationStatus().length > 0}
        >
          <Text style={styles.validateButtonText}>
            {loading ? 'Processing...' : '🔍 Preview Split'}
          </Text>
        </TouchableOpacity>
      </View>

      {renderPreviewModal()}
      
      {/* Bottom padding for web scrolling */}
      <View style={{
        height: Platform.OS === 'web' ? 100 : 20,
        minHeight: Platform.OS === 'web' ? 100 : 0
      }} />
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0a0a0a',
    ...Platform.select({
      web: {
        height: '100vh',
        overflow: 'auto',
        WebkitOverflowScrolling: 'auto',
        scrollBehavior: 'smooth',
      },
    }),
  },
  webScrollView: {
    ...Platform.select({
      web: {
        height: '100vh',
        maxHeight: '100vh',
      },
    }),
  },
  webContentContainer: {
    flexGrow: 1,
    minHeight: '100vh',
    paddingBottom: 100,
  },
  scrollContentContainer: {
    flexGrow: 1,
    paddingBottom: Platform.OS === 'web' ? 100 : 40,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    backgroundColor: '#1a1a1a',
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  backButton: {
    color: '#3b82f6',
    fontSize: 16,
    fontWeight: '600',
  },
  headerTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  resetButton: {
    color: '#10b981',
    fontSize: 14,
    fontWeight: '600',
  },
  section: {
    backgroundColor: '#1a1a1a',
    borderRadius: 12,
    padding: 16,
    margin: 16,
    borderWidth: 1,
    borderColor: '#333',
  },
  sectionTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 12,
  },
  subsectionTitle: {
    color: '#ccc',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 8,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  inputLabel: {
    color: '#ccc',
    fontSize: 14,
    fontWeight: '600',
    width: 120,
  },
  input: {
    flex: 1,
    backgroundColor: '#2a2a2a',
    borderRadius: 8,
    padding: 12,
    color: '#fff',
    fontSize: 14,
    borderWidth: 1,
    borderColor: '#444',
  },
  readOnlyInput: {
    backgroundColor: '#1f2937',
    color: '#9ca3af',
  },
  textArea: {
    height: 80,
    textAlignVertical: 'top',
  },
  searchingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    backgroundColor: '#2a2a2a',
    borderRadius: 8,
    marginTop: 8,
  },
  searchingText: {
    color: '#ccc',
    marginLeft: 8,
    fontSize: 14,
  },
  productInfo: {
    backgroundColor: '#374151',
    borderRadius: 8,
    padding: 12,
    marginTop: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#10b981',
  },
  productName: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  productDetails: {
    color: '#ccc',
    fontSize: 12,
    marginBottom: 2,
  },
  splitRatioContainer: {
    gap: 8,
    marginBottom: 16,
  },
  splitRatioButton: {
    backgroundColor: '#2a2a2a',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#444',
  },
  splitRatioButtonActive: {
    backgroundColor: '#3b82f6',
    borderColor: '#3b82f6',
  },
  splitRatioLabel: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  splitRatioDesc: {
    color: '#ccc',
    fontSize: 12,
  },
  splitRatioLabelActive: {
    color: '#fff',
  },
  splitRatioDescActive: {
    color: '#e0e7ff',
  },
  calculationPreview: {
    backgroundColor: '#374151',
    borderRadius: 8,
    padding: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#f59e0b',
  },
  calculationTitle: {
    color: '#f59e0b',
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  calculationText: {
    color: '#fff',
    fontSize: 14,
  },
  actionButtons: {
    padding: 16,
    gap: 12,
  },
  validateButton: {
    backgroundColor: '#3b82f6',
    borderRadius: 8,
    padding: 16,
    alignItems: 'center',
  },
  validateButtonDisabled: {
    backgroundColor: '#6b7280',
  },
  validateButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  validationStatus: {
    backgroundColor: '#374151',
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#f59e0b',
  },
  validationTitle: {
    color: '#f59e0b',
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  validationIssue: {
    color: '#ccc',
    fontSize: 12,
    marginBottom: 2,
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: '#1a1a1a',
    borderRadius: 16,
    width: '95%',
    maxWidth: 500,
    maxHeight: '85%',
    borderWidth: 2,
    borderColor: '#3b82f6',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  modalTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  closeButton: {
    backgroundColor: '#374151',
    borderRadius: 20,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  modalBody: {
    padding: 16,
    maxHeight: 400,
  },
  previewTitle: {
    color: '#10b981',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 12,
  },
  splitSummary: {
    backgroundColor: '#2a2a2a',
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
  },
  summaryLabel: {
    color: '#ccc',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 4,
  },
  summaryValue: {
    color: '#fff',
    fontSize: 14,
    marginBottom: 8,
  },
  actionPreview: {
    backgroundColor: '#dbeafe',
    borderRadius: 8,
    padding: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#3b82f6',
  },
  actionText: {
    color: '#1e40af',
    fontSize: 14,
    textAlign: 'center',
  },
  modalActions: {
    flexDirection: 'row',
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#333',
    gap: 12,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: '#374151',
    borderRadius: 8,
    padding: 12,
    alignItems: 'center',
  },
  cancelButtonText: {
    color: '#ccc',
    fontSize: 14,
    fontWeight: '600',
  },
  confirmButton: {
    flex: 1,
    backgroundColor: '#10b981',
    borderRadius: 8,
    padding: 16,
    alignItems: 'center',
  },
  confirmButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
});

export default ProductSplitScreen;