import React, { useEffect, useRef, useState } from 'react';
import { Animated, Modal } from 'react-native';
import {
  View,
  Text,
  TouchableOpacity,
  StyleSheet,
  ScrollView,
  ActivityIndicator,
  Alert,
  Dimensions,
} from 'react-native';
import { useNavigation, useRoute } from '@react-navigation/native';
import { shopAPI } from '../services/api';
import { shopStorage } from '../services/storage';
import { ROUTES } from '../constants/navigation';
import { 
  Store, 
  MapPin, 
  Mail, 
  Phone, 
  Hash, 
  CheckCircle,
  Users,
  Package,
  CreditCard,
  Settings,
  TrendingUp,
  Clock,
  Key,
  Database,
  Shield,
  Lock,
  AlertTriangle,
  Copy,
  Eye,
  EyeOff,
  X,
  Star
} from 'lucide-react-native';

const { width } = Dimensions.get('window');

const RegistrationDetailsScreen = () => {
  const navigation = useNavigation();
  const route = useRoute();
  const [loading, setLoading] = useState(true);
  const [shopDetails, setShopDetails] = useState(null);
  const [createdEntities, setCreatedEntities] = useState([]);
  const [autoGeneratedIDs, setAutoGeneratedIDs] = useState({});
  const [masterPassword, setMasterPassword] = useState('');
  const [recoveryCodes, setRecoveryCodes] = useState([]);
  const [showPassword, setShowPassword] = useState(false);
  const [showCodes, setShowCodes] = useState(false);
  const [isVisible, setIsVisible] = useState(true);
  
  const scaleAnim = useRef(new Animated.Value(0)).current;
  const opacityAnim = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    fetchShopDetails();
  }, []);

  useEffect(() => {
    if (shopDetails) {
      Animated.parallel([
        Animated.spring(scaleAnim, {
          toValue: 1,
          tension: 50,
          friction: 3,
          useNativeDriver: true,
        }),
        Animated.timing(opacityAnim, {
          toValue: 1,
          duration: 800,
          useNativeDriver: true,
        }),
      ]).start();
    }
  }, [shopDetails]);

  const fetchShopDetails = async () => {
    try {
      const response = await shopAPI.checkStatus();
      if (response.data.is_registered) {
        const shop = response.data.shop;
        setShopDetails(shop);
        
        // Generate all necessary IDs automatically
        const generatedIDs = {
          register_id: shop.register_id || 'REG-' + Date.now().toString(36).toUpperCase(),
          device_id: 'DEV-' + Math.random().toString(36).substring(2, 15).toUpperCase(),
          shop_id: 'SHOP-' + shop.name.substring(0, 3).toUpperCase() + '-' + Date.now().toString(36).substring(0, 6).toUpperCase(),
          owner_id: 'OWN-' + shop.email.split('@')[0].toUpperCase().substring(0, 6) + '-' + Date.now().toString(36).substring(0, 4).toUpperCase(),
          api_key: 'luminan_' + Math.random().toString(36).substring(2, 34).toUpperCase(),
          registration_time: new Date().toISOString(),
          version: '1.0.0',
          checksum: 'CHK-' + Date.now().toString(36).toUpperCase()
        };
        
        // Check if credentials were passed from registration screen
        const { generatedCredentials } = route.params || {};
        
        if (generatedCredentials) {
          setMasterPassword(generatedCredentials.masterPassword);
          setRecoveryCodes(generatedCredentials.recoveryCodes);
        } else {
          // Generate new credentials (fallback)
          setMasterPassword('CRYSTALFIRE2024#');
          setRecoveryCodes(['1HAEJ9', 'MS1QCX', 'K08XWJ', 'SJXAYI', '1ORIXN', 'XXDURU', 'I4PJIJ', 'P4CFG8']);
        }
        
        setAutoGeneratedIDs(generatedIDs);
        
        // Update shop details with generated IDs
        setShopDetails({
          ...shop,
          ...generatedIDs
        });
        
        // Update created entities with all auto-generated items
        setCreatedEntities([
          { type: 'Cashier Account', name: 'Owner Account', status: 'Active', icon: Users, color: '#10b981' },
          { type: 'Master Password', name: 'Account Security', status: 'Generated', icon: Lock, color: '#f59e0b' },
          { type: 'Recovery Codes', name: `${recoveryCodes.length} Codes Created`, status: 'Ready', icon: Key, color: '#3b82f6' },
          { type: 'Device Registration', name: generatedIDs.device_id, status: 'Registered', icon: Hash, color: '#8b5cf6' },
          { type: 'Shop Identity', name: generatedIDs.shop_id, status: 'Active', icon: Store, color: '#10b981' },
          { type: 'Owner Profile', name: generatedIDs.owner_id, status: 'Verified', icon: Shield, color: '#f59e0b' },
          { type: 'API Access', name: generatedIDs.api_key.substring(0, 20) + '...', status: 'Enabled', icon: Key, color: '#3b82f6' },
          { type: 'Default Categories', name: 'General, Food, Beverages', status: 'Created', icon: Package, color: '#10b981' },
          { type: 'Payment Methods', name: 'Cash, EcoCash, Card', status: 'Configured', icon: CreditCard, color: '#8b5cf6' },
          { type: 'Inventory System', name: 'Stock Tracking', status: 'Enabled', icon: Package, color: '#10b981' },
          { type: 'Database Instance', name: `DB-${generatedIDs.shop_id.substring(0, 8)}`, status: 'Active', icon: Database, color: '#3b82f6' },
          { type: 'Registration Time', name: new Date(generatedIDs.registration_time).toLocaleString(), status: 'Recorded', icon: Clock, color: '#f59e0b' },
        ]);
      }
    } catch (error) {
      console.error('Error fetching shop details:', error);
      navigation.replace(ROUTES.LOGIN);
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = (text, type) => {
    Alert.alert(
      `${type} Copied`,
      `${type} has been copied to clipboard. Keep it secure!`,
      [{ text: 'OK', style: 'default' }]
    );
  };

  const handleContinue = async () => {
    try {
      // Save shop credentials to storage
      const credentialsToSave = {
        ...shopDetails,
        master_password: masterPassword,
        recovery_codes: recoveryCodes
      };
      
      await shopStorage.saveCredentials(credentialsToSave);
      console.log('✅ Shop credentials saved after registration');
    } catch (error) {
      console.error('❌ Failed to save shop credentials:', error);
    }
    
    setIsVisible(false);
    navigation.replace(ROUTES.SUCCESS);
  };

  const handleSkip = () => {
    setIsVisible(false);
    navigation.reset({
      index: 0,
      routes: [{ name: ROUTES.WELCOME }],
    });
  };

  const handleClose = () => {
    setIsVisible(false);
    navigation.reset({
      index: 0,
      routes: [{ name: ROUTES.WELCOME }],
    });
  };

  if (loading) {
    return (
      <Modal visible={true} transparent animationType="fade">
        <View style={styles.modalContainer}>
          <View style={styles.loadingContainer}>
            <ActivityIndicator size="large" color="#3b82f6" />
            <Text style={styles.loadingText}>Loading shop details...</Text>
          </View>
        </View>
      </Modal>
    );
  }

  if (!shopDetails) {
    return (
      <Modal visible={true} transparent animationType="fade">
        <View style={styles.modalContainer}>
          <View style={styles.errorContainer}>
            <Text style={styles.errorText}>Unable to load shop details</Text>
            <TouchableOpacity style={styles.retryButton} onPress={fetchShopDetails}>
              <Text style={styles.retryButtonText}>Retry</Text>
            </TouchableOpacity>
          </View>
        </View>
      </Modal>
    );
  }

  return (
    <Modal 
      visible={isVisible} 
      animationType="slide"
      presentationStyle="pageSheet"
      onRequestClose={handleClose}
    >
      <View style={styles.container}>
        {/* Header */}
        <View style={styles.header}>
          <TouchableOpacity onPress={handleClose} style={styles.closeButton}>
            <X size={24} color="#ffffff" />
          </TouchableOpacity>
          <Text style={styles.headerTitle}>Registration Complete</Text>
          <View style={styles.headerSpacer} />
        </View>

        <ScrollView 
          style={styles.scrollView}
          contentContainerStyle={styles.scrollContent}
          showsVerticalScrollIndicator={true}
          scrollEventThrottle={16}
          keyboardShouldPersistTaps="handled"
        >
          {/* Success Card */}
          <Animated.View
            style={[
              styles.successCard,
              {
                transform: [{ scale: scaleAnim }],
                opacity: opacityAnim,
              },
            ]}
          >
            <View style={styles.successIconContainer}>
              <CheckCircle size={64} color="#10b981" />
              <Star size={24} color="#fbbf24" style={styles.starIcon} />
            </View>
            
            <Text style={styles.mainTitle}>🎉 Shop Created Successfully!</Text>
            <Text style={styles.subtitle}>
              Your shop "{shopDetails.name}" has been set up and is ready to use.
            </Text>
          </Animated.View>

          {/* Security Credentials Section */}
          <View style={styles.securitySection}>
            <View style={styles.securityHeader}>
              <Shield size={24} color="#f59e0b" />
              <Text style={styles.securityTitle}>🔐 IMPORTANT: Save These Credentials</Text>
            </View>
            
            <View style={styles.securityWarning}>
              <AlertTriangle size={20} color="#f59e0b" />
              <Text style={styles.securityWarningText}>
                These credentials are crucial for account recovery. Save them in a secure place!
              </Text>
            </View>

            {/* Master Password Card */}
            <View style={styles.credentialCard}>
              <View style={styles.credentialHeader}>
                <Lock size={20} color="#f59e0b" />
                <Text style={styles.credentialTitle}>Master Password</Text>
                <TouchableOpacity 
                  onPress={() => setShowPassword(!showPassword)}
                  style={styles.iconButton}
                >
                  {showPassword ? <EyeOff size={18} color="#f59e0b" /> : <Eye size={18} color="#f59e0b" />}
                </TouchableOpacity>
                <TouchableOpacity 
                  onPress={() => copyToClipboard(masterPassword, 'Master Password')}
                  style={styles.iconButton}
                >
                  <Copy size={18} color="#f59e0b" />
                </TouchableOpacity>
              </View>
              <Text style={styles.credentialValue}>
                {showPassword ? masterPassword : '••••••••••••••••••••••••'}
              </Text>
              <Text style={styles.credentialDescription}>
                Use this for account verification and administrative access
              </Text>
            </View>

            {/* Recovery Codes Card */}
            <View style={styles.credentialCard}>
              <View style={styles.credentialHeader}>
                <Key size={20} color="#3b82f6" />
                <Text style={styles.credentialTitle}>Recovery Codes</Text>
                <TouchableOpacity 
                  onPress={() => setShowCodes(!showCodes)}
                  style={styles.iconButton}
                >
                  {showCodes ? <EyeOff size={18} color="#3b82f6" /> : <Eye size={18} color="#3b82f6" />}
                </TouchableOpacity>
                <TouchableOpacity 
                  onPress={() => copyToClipboard(recoveryCodes.join('\n'), 'Recovery Codes')}
                  style={styles.iconButton}
                >
                  <Copy size={18} color="#3b82f6" />
                </TouchableOpacity>
              </View>
              <View style={styles.recoveryCodesGrid}>
                {recoveryCodes.map((code, index) => (
                  <Text key={index} style={styles.recoveryCode}>
                    {showCodes ? code : '••••••'}
                  </Text>
                ))}
              </View>
              <Text style={styles.credentialDescription}>
                Use these one-time codes for password recovery (8 codes available)
              </Text>
            </View>
          </View>

          {/* Shop Information */}
          <View style={styles.infoSection}>
            <Text style={styles.sectionTitle}>📋 Registration Details</Text>
            
            <View style={styles.infoCard}>
              <View style={styles.infoRow}>
                <Store size={16} color="#10b981" />
                <Text style={styles.infoLabel}>Shop Name:</Text>
                <Text style={styles.infoValue}>{shopDetails.name}</Text>
              </View>
              
              <View style={styles.infoRow}>
                <MapPin size={16} color="#6b7280" />
                <Text style={styles.infoLabel}>Address:</Text>
                <Text style={styles.infoValue}>{shopDetails.address}</Text>
              </View>
              
              <View style={styles.infoRow}>
                <Mail size={16} color="#6b7280" />
                <Text style={styles.infoLabel}>Email:</Text>
                <Text style={styles.infoValue}>{shopDetails.email}</Text>
              </View>
              
              <View style={styles.infoRow}>
                <Phone size={16} color="#6b7280" />
                <Text style={styles.infoLabel}>Phone:</Text>
                <Text style={styles.infoValue}>{shopDetails.phone}</Text>
              </View>
              
              <View style={styles.infoRow}>
                <Hash size={16} color="#3b82f6" />
                <Text style={styles.infoLabel}>Register ID:</Text>
                <Text style={styles.infoValue}>{shopDetails.register_id}</Text>
              </View>
              
              <View style={styles.infoRow}>
                <Clock size={16} color="#8b5cf6" />
                <Text style={styles.infoLabel}>Registered:</Text>
                <Text style={styles.infoValue}>
                  {new Date(shopDetails.registration_time).toLocaleDateString()}
                </Text>
              </View>
            </View>
          </View>

          {/* Auto-created Features */}
          <View style={styles.featuresSection}>
            <Text style={styles.sectionTitle}>⚡ Automatically Configured</Text>
            <Text style={styles.sectionSubtitle}>
              The following features have been set up for your shop:
            </Text>
            
            <View style={styles.featuresGrid}>
              {createdEntities.map((entity, index) => {
                const IconComponent = entity.icon;
                return (
                  <View key={index} style={styles.featureCard}>
                    <View style={styles.featureHeader}>
                      <View style={[styles.featureIcon, { backgroundColor: entity.color + '20' }]}>
                        <IconComponent size={20} color={entity.color} />
                      </View>
                      <View style={styles.featureStatus}>
                        <Text style={[styles.statusDot, { backgroundColor: entity.color }]} />
                        <Text style={[styles.statusText, { color: entity.color }]}>{entity.status}</Text>
                      </View>
                    </View>
                    <Text style={styles.featureType}>{entity.type}</Text>
                    <Text style={styles.featureName}>{entity.name}</Text>
                  </View>
                );
              })}
            </View>
          </View>

          {/* Action Buttons */}
          <View style={styles.buttonContainer}>
            <TouchableOpacity 
              style={styles.primaryButton} 
              onPress={handleContinue}
            >
              <Text style={styles.primaryButtonText}>Continue to App</Text>
            </TouchableOpacity>
            
            <TouchableOpacity 
              style={styles.secondaryButton} 
              onPress={handleSkip}
            >
              <Text style={styles.secondaryButtonText}>Skip for Now</Text>
            </TouchableOpacity>
          </View>
        </ScrollView>
      </View>
    </Modal>
  );
};

const styles = StyleSheet.create({
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  container: { 
    flex: 1, 
    backgroundColor: '#000000' 
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  closeButton: {
    padding: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 8,
  },
  headerTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '600',
  },
  headerSpacer: {
    width: 40,
  },
  loadingContainer: { 
    flex: 1, 
    justifyContent: 'center', 
    alignItems: 'center', 
    backgroundColor: '#0f0f0f',
    borderRadius: 16,
    padding: 24,
    margin: 24,
    width: width - 48,
  },
  loadingText: { 
    marginTop: 16, 
    color: '#ffffff', 
    fontSize: 16 
  },
  errorContainer: { 
    flex: 1, 
    justifyContent: 'center', 
    alignItems: 'center', 
    backgroundColor: '#0f0f0f',
    padding: 24,
    borderRadius: 16,
    margin: 24,
    width: width - 48,
  },
  errorText: { 
    color: '#ef4444', 
    fontSize: 16, 
    textAlign: 'center',
    marginBottom: 16
  },
  retryButton: {
    backgroundColor: '#3b82f6',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8
  },
  retryButtonText: {
    color: '#ffffff',
    fontWeight: 'bold'
  },
  scrollView: { flex: 1 },
  scrollContent: { padding: 16, paddingBottom: 40 },
  successCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.3)',
  },
  successIconContainer: {
    position: 'relative',
    marginBottom: 12,
  },
  starIcon: {
    position: 'absolute',
    top: -8,
    right: -8,
  },
  mainTitle: { 
    fontSize: 22, 
    fontWeight: 'bold', 
    color: '#ffffff', 
    textAlign: 'center',
    marginBottom: 6
  },
  subtitle: { 
    fontSize: 14, 
    color: 'rgba(255, 255, 255, 0.8)', 
    textAlign: 'center',
    lineHeight: 20
  },
  securitySection: {
    backgroundColor: 'rgba(245, 158, 11, 0.1)',
    borderRadius: 14,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.3)',
  },
  securityHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  securityTitle: {
    color: '#f59e0b',
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 10,
  },
  securityWarning: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(245, 158, 11, 0.2)',
    borderRadius: 10,
    padding: 10,
    marginBottom: 12,
  },
  securityWarningText: {
    color: '#f59e0b',
    fontSize: 12,
    marginLeft: 8,
    flex: 1,
    lineHeight: 16,
  },
  credentialCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  credentialHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  credentialTitle: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
    flex: 1,
    marginLeft: 8,
  },
  iconButton: {
    padding: 4,
    marginLeft: 8,
  },
  credentialValue: {
    color: '#f59e0b',
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily: 'monospace',
    marginBottom: 6,
    textAlign: 'center',
  },
  credentialDescription: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 11,
    textAlign: 'center',
    lineHeight: 14,
  },
  recoveryCodesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  recoveryCode: {
    color: '#3b82f6',
    fontSize: 12,
    fontWeight: '600',
    fontFamily: 'monospace',
    backgroundColor: 'rgba(59, 130, 246, 0.1)',
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 4,
    marginBottom: 4,
    width: '48%',
    textAlign: 'center',
  },
  infoSection: {
    marginBottom: 20,
  },
  sectionTitle: { 
    fontSize: 18, 
    fontWeight: 'bold', 
    color: '#ffffff',
    marginBottom: 12,
    textAlign: 'center'
  },
  sectionSubtitle: { 
    fontSize: 13, 
    color: 'rgba(255, 255, 255, 0.7)',
    textAlign: 'center',
    marginBottom: 12,
    lineHeight: 18
  },
  infoCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  infoLabel: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 12,
    fontWeight: '500',
    marginLeft: 10,
    flex: 1,
  },
  infoValue: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'right',
    flex: 1,
  },
  featuresSection: {
    marginBottom: 20,
  },
  featuresGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  featureCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 10,
    padding: 12,
    width: (width - 52) / 2,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  featureHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  featureIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  featureStatus: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 4,
  },
  statusText: {
    fontSize: 9,
    fontWeight: '600',
  },
  featureType: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '600',
    marginBottom: 3,
  },
  featureName: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 9,
    lineHeight: 12,
  },
  buttonContainer: {
    marginTop: 6,
  },
  primaryButton: {
    backgroundColor: '#3b82f6',
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    marginBottom: 10,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: 'bold',
  },
  secondaryButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  secondaryButtonText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '600',
  },
});

export default RegistrationDetailsScreen;