// Navigation route names
export const ROUTES = {
  WELCOME: 'Welcome',
  REGISTER: 'Register',
  LOGIN: 'Login',
  CASHIER_DASHBOARD: 'CashierDashboard',
  FORGOT_PASSWORD: 'ForgotPassword',
  CASHIER_RESET_PASSWORD: 'CashierResetPassword',
  REGISTRATION_DETAILS: 'RegistrationDetails',
  SUCCESS: 'Success',
  OWNER_DASHBOARD: 'OwnerDashboard',
  SETTINGS: 'Settings',
  STAFF_MANAGEMENT: 'StaffManagement',
  STAFF_CONTRACT: 'StaffContract',
  CASHIER_REGISTER: 'CashierRegister',
  INVENTORY_AUDIT_TRAIL: 'InventoryAuditTrail',
  ORDER_CONFIRMATION: 'OrderConfirmation',
  INVENTORY_RECEIVING: 'InventoryReceiving',
  RESTOCK_MANAGER: 'RestockManager',
  STOCK_TRANSFER: 'StockTransfer',
  STOCK_TRANSFER_HISTORY: 'StockTransferHistory',
  STOCK_TAKE: 'StockTake',
  STOCK_VALUATION: 'StockValuation',
  POS_PRICE: 'POSPrice',
  SALES_AND_REFUNDS: 'SalesAndRefunds',
  CASHIER_SALES: 'CashierSales',
  CASHIER_COUNT: 'CashierCount',
  CASHIER_PRODUCT_RECEIVING: 'CashierProductReceiving',
  QUICK_PRODUCTS: 'QuickProducts',
  // License Management routes
  LICENSE_FIRST_LOGIN: 'LicenseFirstLogin',
  LICENSE_RENEWAL: 'LicenseRenewal',
  LICENSE_MANAGEMENT: 'LicenseManagement',
  // Sales Command Center routes
  SALES_DASHBOARD: 'SalesDashboard',
  SALES_LEDGER: 'SalesLedger',
  SALES_AUDIT_TRAIL: 'SalesAuditTrail',

  EOD_RECONCILIATION: 'EODReconciliation',
  WASTE_SCREEN: 'WasteScreen',
  START_OF_DAY: 'StartOfDay',
  PRODUCT_SPLIT: 'ProductSplit',
  HALF_PRODUCTS: 'HalfProducts',
  PRODUCT_MANAGEMENT: 'ProductManagement',
  WEIGHT_PRODUCTS: 'WeightProducts',
  SUPPLIER_MANAGEMENT: 'SupplierManagement',
  STOCK_MOVEMENTS: 'StockMovements',
  PRICE_COMPARISON: 'PriceComparison',
  DEMAND_FORECASTING: 'DemandForecasting',
  STAFF_LUNCH: 'StaffLunch',
  EXCHANGE_RATE_MANAGEMENT: 'ExchangeRateManagement',
  DRAWER_MANAGEMENT: 'DrawerManagement',
  CASHIER_HISTORY: 'CashierHistory',
};

// Screen titles
export const SCREEN_TITLES = {
  [ROUTES.WELCOME]: 'Welcome',
  [ROUTES.REGISTER]: 'Create Shop',
  [ROUTES.LOGIN]: 'Sign In',
  [ROUTES.CASHIER_DASHBOARD]: 'Cashier Dashboard',
  [ROUTES.FORGOT_PASSWORD]: 'Forgot Password',
  [ROUTES.CASHIER_RESET_PASSWORD]: 'Cashier Password Reset',
  [ROUTES.REGISTRATION_DETAILS]: 'Registration Details',
  [ROUTES.SUCCESS]: 'Success',
  [ROUTES.OWNER_DASHBOARD]: 'Owner Dashboard',
  [ROUTES.SETTINGS]: 'Settings',
  [ROUTES.STAFF_MANAGEMENT]: 'Staff Management',
  [ROUTES.STAFF_CONTRACT]: 'Staff Contract',
  [ROUTES.CASHIER_REGISTER]: 'Staff Registration',
  [ROUTES.INVENTORY_AUDIT_TRAIL]: 'Inventory Audit Trail',
  [ROUTES.ORDER_CONFIRMATION]: 'Order Confirmation',
  [ROUTES.INVENTORY_RECEIVING]: 'Inventory Receiving',
  [ROUTES.RESTOCK_MANAGER]: 'Restock Manager',
  [ROUTES.STOCK_TRANSFER]: 'Stock Transfer',
  [ROUTES.STOCK_TRANSFER_HISTORY]: 'Transfer History',
  [ROUTES.STOCK_TAKE]: 'Stock Take',
  [ROUTES.STOCK_VALUATION]: 'Stock Valuation',
  [ROUTES.POS_PRICE]: 'POS Price Labels',
  [ROUTES.SALES_AND_REFUNDS]: 'Sales & Refunds',
  [ROUTES.CASHIER_COUNT]: 'Cashier Cash Count',
  [ROUTES.CASHIER_PRODUCT_RECEIVING]: 'Cashier Product Receiving',
  [ROUTES.QUICK_PRODUCTS]: 'Quick Products',
  // License Management titles
  [ROUTES.LICENSE_FIRST_LOGIN]: 'License Required',
  [ROUTES.LICENSE_RENEWAL]: 'License Renewal',
  [ROUTES.LICENSE_MANAGEMENT]: 'License Management',
  // Sales Command Center titles
  [ROUTES.SALES_DASHBOARD]: 'Sales Dashboard',
  [ROUTES.SALES_LEDGER]: 'Sales Ledger',
  [ROUTES.SALES_AUDIT_TRAIL]: 'Sales Audit Trail',

  [ROUTES.EOD_RECONCILIATION]: 'EOD Reconciliation',
  [ROUTES.WASTE_SCREEN]: 'Waste Management',
  [ROUTES.START_OF_DAY]: 'Start of Day',
  [ROUTES.PRODUCT_SPLIT]: 'Product Split',
  [ROUTES.HALF_PRODUCTS]: 'Half Products',
  [ROUTES.PRODUCT_MANAGEMENT]: 'Product Management',
  [ROUTES.WEIGHT_PRODUCTS]: 'Weight Products',
  [ROUTES.SUPPLIER_MANAGEMENT]: 'Supplier Management',
  [ROUTES.STOCK_MOVEMENTS]: 'Stock Movements',
  [ROUTES.PRICE_COMPARISON]: 'Price Comparison',
  [ROUTES.DEMAND_FORECASTING]: 'Demand Forecasting',
  [ROUTES.STAFF_LUNCH]: 'Staff Lunch',
  [ROUTES.EXCHANGE_RATE_MANAGEMENT]: 'Exchange Rate Management',
  [ROUTES.DRAWER_MANAGEMENT]: 'Drawer Management',
  [ROUTES.CASHIER_HISTORY]: 'Cashier History & Performance',
};